CREATE OR ALTER PROCEDURE [dbo].[besure_einvoice_gst_create]
@Business varchar(8),
@Invoiceno VARCHAR(50),
@InvoiceDate Date,
@Type varchar(10),
@SubType varchar(10),
@Location varchar(50),
@LocationState varchar(50),
@LocationStateCode varchar(50),
@LocationGSTIN varchar(16),
@CustomerName varchar(64),
@CustomerAddress1 varchar(128),
@CustomerCity varchar(32),
@CustomerState varchar(64),
@CustomerStateCode int,
@CustomerPincode varchar(8),
@CustomerGSTIN varchar(16),
@CustomerShipName varchar(64),
@CustomerShipAddress1 varchar(128),
@CustomerShipCity varchar(64),
@CustomerShipState varchar(64),
@CustomerShipStateCode int,
@CustomerShipPincode varchar(8),
@CustShipGSTIN varchar(16),
@TaxableValue decimal(16,2),
@NETAmt decimal(16,2)=0,
@Sgst decimal(16,2),
@Cgst decimal(16,2),
@Igst decimal(16,2),
@BILLTOCODE varchar(20),
@SHIPTOCODE varchar(20),
@UniqueID varchar(128),
@CreatedBy int,
@ContractInvoiceDetail NVARCHAR(MAX)

AS
	SET NOCOUNT ON;
    SET XACT_ABORT ON;
	Declare @InvoiceId INT; 
	
BEGIN 
BEGIN TRANSACTION

DECLARE @HeaderUniqueID VARCHAR(256)=(SELECT NEWID());
INSERT INTO SalesRegisterHeader(
    Business,
	Invoiceno,
	InvoiceDate,
	[Type],
	SubType,
	Cancel,
	[Location],
	LocationState,
	LocationStateCode,
	LocationGSTIN,
	CustomerName,
	CustomerAddress1,
	CustomerCity,
	CustomerState,
	CustomerStateCode,
	CustomerPincode,
	CustomerGSTIN,
	CustomerShipName,
	CustomerShipAddress1,
	CustomerShipCity,
	CustomerShipState,
	CustomerShipStateCode,
	CustomerShipPincode,
	CustShipGSTIN,
	TaxableValue,
	CGSTAmount,
	SGSTAmount,
	IGSTAmount,
	NETAmt,
	UniqueID,
	BILLTOCODE,
	SHIPTOCODE,
	RAISEDFROM
	)
	values(
	    @Business,
		@Invoiceno,
		@InvoiceDate,
		@Type,
		@SubType,
		0,
		@Location,
		@LocationState,
		@LocationStateCode,
		@LocationGSTIN,
		@CustomerName,
	    @CustomerAddress1,
	    @CustomerCity,
	    @CustomerState,
	    @CustomerStateCode,
	    @CustomerPincode,
	    @CustomerGSTIN,
		@CustomerShipName,
		@CustomerShipAddress1,
		@CustomerShipCity,
		@CustomerShipState,
		@CustomerShipStateCode,
		@CustomerShipPincode,
		@CustShipGSTIN,
	   @TaxableValue,
		@Cgst,
		@Sgst,
		@Igst,
	    @NETAmt,
		@HeaderUniqueID,
		@BILLTOCODE,
		@SHIPTOCODE,
		'B'
	);

	INSERT INTO SalesRegisterDetails(
	Invoiceno,
	DescofService,
	SACCode,
	Qty,
	UOM,
	RateperUnit,
	Total,
	DiscountValue,
	TaxableValue,
	CGSTRate,
	CGSTAmount,
	SGSTRate,
	SGSTAmount,
	IGSTRate,
	IGSTAmount,
	TaxType,
	TCSValue,
	TCSRate,
	HeaderUniqueID,
	Uniqueid
	) 
		SELECT
	@Invoiceno ,
	ItemDescription,
	ServicingAccountingCode,
	Quantity,
	'OTH',
	Rate,
	((Quantity*Rate-ISNULL(Discount, 0))+ (Quantity*Rate-ISNULL(Discount, 0))*Sgst/100 + (Quantity*Rate-ISNULL(Discount, 0))*Cgst/100 +(Quantity*Rate-ISNULL(Discount, 0))*Igst/100),
	ISNULL(Discount, 0),
	Amount-ISNULL(Discount, 0),
	Cgst,
	(Quantity*Rate-ISNULL(Discount, 0))*Cgst/100 ,
	Sgst,
    (Quantity*Rate-ISNULL(Discount, 0))*Sgst/100 ,
    Igst, 
    (Quantity*Rate-ISNULL(Discount, 0))*Igst/100 ,
	(CASE WHEN @Sgst > 0 THEN 'SGST' ELSE 'IGST' END),
	0,
	0,
	@HeaderUniqueID,
	(SELECT NEWID())
    FROM OPENJSON(@ContractInvoiceDetail)
	WITH(
	ItemDescription VARCHAR(128),
	ServicingAccountingCode VARCHAR(8),
	Quantity DECIMAL(16,2),
	Unit DECIMAL(16,2),
	Rate DECIMAL(16,2),
	Amount DECIMAL(16,2),
	Discount DECIMAL(16,2),
	Sgst DECIMAL(16,2),
	Cgst DECIMAL(16,2),
	Igst DECIMAL(16,2),
	NetAmount DECIMAL(16,2)
	)

	COMMIT TRANSACTION
END 

