CREATE OR ALTER   PROCEDURE [dbo].[contract_create]
	@AccelLocation INT,
	@CustomerInfoId INT,
	@SalesContactPerson INT,
	@AgreementTypeId INT,
	@ContractValue DECIMAL(16,2),
	@AmcValue DECIMAL(16,2),
	@FmsValue DECIMAL(16,2),
	@StartDate DATE,
	@EndDate DATE,
	@BookingType INT,
	@BookingDate DATE,
	@BookingValueDate DATE,
	@QuotationReferenceNumber VARCHAR(64),
	@QuotationReferenceDate DATE,
	@PoNumber VARCHAR(64),
	@PoDate DATE,
	@IsPreformanceGuarentee BIT,
	@PerformanceGuaranteeAmount DECIMAL(16,2),
	@IsMultiSite BIT,
	@IsPreAmcNeeded BIT,
	@SiteCount SMALLINT,
	@PaymentMode INT,
	@PaymentFrequency INT,
	@CreditPeriod INT,
	@ServiceMode INT,
	@ServiceWindow INT,
	@IsPreventiveMaintenanceNeeded BIT,
	@IsSez BIT,
	@IsBackToBackAllowed BIT,
	@BackToBackScopeId INT,
	@IsStandByFullUnitRequired BIT,
	@IsStandbyImpressStockRequired BIT,
	@PmFrequency INT, 
	@CreatedBy INT,
	@ContractInvoicePrerequisite NVARCHAR(MAX),
	@ContractId INT OUTPUT
AS
BEGIN
	SET NOCOUNT ON;
    SET XACT_ABORT ON;
	DECLARE @ContractStatusId INT;
	BEGIN TRANSACTION

	SELECT @ContractStatusId = Id FROM MasterEntityData WHERE Code ='CTS_PGRS'
	--Insert Into Contract Table
	INSERT INTO Contract
		(TenantOfficeId,
		CustomerInfoId,
		CustomerId,
		SalesContactPersonId,
		AgreementTypeId,
		ContractValue,
		AmcValue,
		FmsValue,
		StartDate,
		EndDate,
		CallExpiryDate,
		BookingTypeId,
		BookingDate,
		BookingValueDate,
		QuotationReferenceNumber,
		QuotationReferenceDate,
		PoNumber,
		PoDate,
		IsPerformanceGuaranteeRequired,
		PerformanceGuaranteeAmount,
		IsMultiSite,
		SiteCount,
		IsPreAmcNeeded,
		PaymentModeId,
		PaymentFrequencyId,
		CreditPeriod,
		ServiceModeId,
		ServiceWindowId,
		IsPmRequired,
		IsSez,
		IsBackToBackAllowed,
		BackToBackScopeId,
		IsStandByFullUnitRequired,
		IsStandByImprestStockRequired,
		PmFrequencyId,			
		CreatedBy,
		CreatedOn,
		ContractStatusId)
    VALUES
		(@AccelLocation ,
		@CustomerInfoId,
		(SELECT CustomerId FROM CustomerInfo WHERE Id=@CustomerInfoId),
		@SalesContactPerson, 
		@AgreementTypeId,
		@ContractValue ,
		@AmcValue,
		@FmsValue,
		@StartDate ,
		@EndDate ,
		@EndDate ,
		@BookingType,
		@BookingDate ,
		@BookingValueDate ,
		@QuotationReferenceNumber ,
		@QuotationReferenceDate ,
		@PoNumber ,
		@PoDate ,
		@IsPreformanceGuarentee ,
		@PerformanceGuaranteeAmount,
		@IsMultiSite ,
		@SiteCount ,
		@IsPreAmcNeeded,
		@PaymentMode ,
		@PaymentFrequency ,
		@CreditPeriod ,
		@ServiceMode ,
		@ServiceWindow ,
		@IsPreventiveMaintenanceNeeded ,
		@IsSez ,
		@IsBackToBackAllowed ,
		@BackToBackScopeId ,
		@IsStandByFullUnitRequired ,
		@IsStandbyImpressStockRequired,
		@PmFrequency , 
		@CreatedBy,
		GETUTCDATE(),
		@ContractStatusId)

	SET @ContractId = SCOPE_IDENTITY()

	--Insert Into @ContractInvoicePrerequisite Table from the Json
	INSERT INTO ContractInvoicePrerequisite (
									InvoicePrerequisiteId,
									DocumentName ,
									[Description],
									ContractId,
									CreatedBy,
									CreatedOn)
	SELECT
			Id,
			DocumentName ,
			[Description],
			@ContractId,
			@CreatedBy,
			GETUTCDATE()
	FROM OPENJSON(@ContractInvoicePrerequisite)
	WITH
	(Id INT,
	DocumentName VARCHAR(64),
	[Description] VARCHAR(128))
	COMMIT TRANSACTION;
END