using BeSureApi.Models;
using database.Models;

namespace database.Seeder.Staging
{
    public class ContractSeeder
    {
        public IEnumerable<Contract> GetData()
        {
            return new List<Contract>
            {
                new Contract
                {
                    Id = 1,
                    ContractNumber = "ACC/MAS/2023/0004",
                    CustomerInfoId = 3,
                    CustomerId = 3,
                    TenantOfficeId = 20,
                    AgreementTypeId = 4,
                    BookingTypeId = 6,
                    BookingDate = DateTime.Parse("2023-04-06").Date,
                    BookingValueDate = DateTime.Parse("2023-04-16").Date,
                    ContractValue = 30000,
                    AmcValue = 10000,
                    FmsValue = 20000,
                    QuotationReferenceNumber = "ESSIL/20/MAS/00117",
                    QuotationReferenceDate = DateTime.Parse("2023-04-06").Date,
                    PoNumber = "4700098814",
                    PoDate = DateTime.Parse("2023-04-06").Date,
                    StartDate = DateTime.Parse("2023-05-08").Date,
                    EndDate = DateTime.Parse("2025-05-07").Date,
                    CallExpiryDate=DateTime.Parse("2025-05-07").Date,
                    IsPerformanceGuaranteeRequired = false,
                    PerformanceGuaranteeAmount = null,
                    IsMultiSite = true,
                    SiteCount = 6,
                    ServiceModeId = 11,
                    PaymentModeId = 16,
                    PaymentFrequencyId = 1,
                    IsSez = false,
                    IsPmRequired = true,
                    PmFrequencyId = 18,
                    IsBackToBackAllowed = false,
                    BackToBackScopeId = 83,
                    CreditPeriod = 169,
                    ServiceWindowId = 73,
                    IsStandByFullUnitRequired = false,
                    IsStandByImprestStockRequired = false,
                    OldContractId = null,
                    ContractStatusId = 69,
                    SalesContactPersonId = 26,
                    CreatedBy = 10,
                    CreatedOn = DateTime.Parse("2023-04-06"),
                    IsDeleted = false,
                    DeletedBy = null,
                    DeletedOn = null,
                    UpdatedBy = null,
                    UpdatedOn = null,
                    FirstApprovedOn = DateTime.Parse("2023-05-01").Date,
                    FirstApproverId = 13,
                    SecondApprovedOn = DateTime.Parse("2023-05-07").Date,
                    SecondApproverId = 14
                },
                new Contract
                {
                    Id = 2,
                    ContractNumber = "ACC/BLR/2023/0061",
                    CustomerInfoId = 6,
                    CustomerId = 6,
                    TenantOfficeId = 18,
                    AgreementTypeId = 4,
                    BookingTypeId = 6,
                    BookingDate = DateTime.Parse("2023-01-10").Date,
                    BookingValueDate = DateTime.Parse("2023-04-16").Date,
                    ContractValue = 1000000,
                    AmcValue = 0,
                    FmsValue = 1000000,
                    QuotationReferenceNumber = "ESSIL/20/BLR/00561",
                    QuotationReferenceDate = DateTime.Parse("2023-04-06").Date,
                    PoNumber = "40969",
                    PoDate = DateTime.Parse("2023-04-06").Date,
                    StartDate = DateTime.Parse("2023-01-16").Date,
                    EndDate = DateTime.Parse("2025-01-15").Date,
                    CallExpiryDate=DateTime.Parse("2025-01-15").Date,
                    IsPerformanceGuaranteeRequired = false,
                    PerformanceGuaranteeAmount = null,
                    IsMultiSite = true,
                    SiteCount = 6,
                    ServiceModeId = 11,
                    PaymentModeId = 16,
                    PaymentFrequencyId = 1,
                    IsSez = false,
                    IsPmRequired = true,
                    PmFrequencyId = 18,
                    IsBackToBackAllowed = false,
                    BackToBackScopeId = 83,
                    CreditPeriod = 169,
                    ServiceWindowId = 73,
                    IsStandByFullUnitRequired = false,
                    IsStandByImprestStockRequired = false,
                    OldContractId = null,
                    ContractStatusId = 69,
                    SalesContactPersonId = 25,
                    CreatedBy = 10,
                    CreatedOn = DateTime.Parse("2023-04-06"),
                    IsDeleted = false,
                    DeletedBy = null,
                    DeletedOn = null,
                    UpdatedBy = null,
                    UpdatedOn = null,
                    FirstApprovedOn = DateTime.Parse("2023-01-10").Date,
                    FirstApproverId = 24,
                    SecondApprovedOn = DateTime.Parse("2023-01-15").Date,
                    SecondApproverId = 14
                },
                new Contract
                {
                    Id = 3,
                    ContractNumber = "",
                    CustomerInfoId = 4,
                    CustomerId = 4,
                    TenantOfficeId = 16,
                    AgreementTypeId = 1,
                    BookingTypeId = 6,
                    BookingDate = DateTime.Parse("2023-01-10").Date,
                    BookingValueDate = DateTime.Parse("2023-01-10").Date,
                    ContractValue = 40000,
                    AmcValue = 40000,
                    FmsValue = 0,
                    QuotationReferenceNumber = "ESSIL/20/COC/00561",
                    QuotationReferenceDate = DateTime.Parse("2023-04-06").Date,
                    PoNumber = "COKAP0014/2021/IT/AMC",
                    PoDate = DateTime.Parse("2023-01-06").Date,
                    StartDate = DateTime.Parse("2023-01-16").Date,
                    EndDate = DateTime.Parse("2025-01-15").Date,
                    IsPerformanceGuaranteeRequired = false,
                    PerformanceGuaranteeAmount = null,
                    IsMultiSite = true,
                    SiteCount = 6,
                    ServiceModeId = 11,
                    PaymentModeId = 16,
                    PaymentFrequencyId = 1,
                    IsSez = false,
                    IsPmRequired = true,
                    PmFrequencyId = 18,
                    IsBackToBackAllowed = false,
                    BackToBackScopeId = 83,
                    CreditPeriod = 169,
                    ServiceWindowId = 73,
                    IsStandByFullUnitRequired = false,
                    IsStandByImprestStockRequired = false,
                    OldContractId = null,
                    ContractStatusId = 67,
                    SalesContactPersonId = 24,
                    CreatedBy = 10,
                    CreatedOn = DateTime.Parse("2023-04-06"),
                    IsDeleted = false,
                    DeletedBy = null,
                    DeletedOn = null,
                    UpdatedBy = null,
                    UpdatedOn = null,
                    FirstApprovedOn = null,
                    FirstApproverId = null,
                    SecondApprovedOn = null,
                    SecondApproverId = null
                }
            };
        }
    };
}
