using BeSureApi.Models;
using Bogus;
using database.Models;

namespace database.Seeder.Staging
{
    public class CustomerInfoSeeder
    {
        public IEnumerable<CustomerInfo> GetData()
        {
            return new List<CustomerInfo>
            {
            new CustomerInfo
            {
                Id = 1,
                CustomerId = 1,
                Name = "Edelweiss Financial Advisors Ltd",
                NameOnPrint = "Edelweiss Financial Advisors Ltd",
                CustomerGroupId = null,
                TenantOfficeId = 1,
                PrimaryContactName = "DARSHAN DESAI",
                PrimaryContactEmail = "fathima.beevi@accelits.com",
                PrimaryContactPhone = "9227160020",
                PanNumber = "Not Available",
                TinNumber = "Not Available",
                TanNumber = "Not Available",
                CinNumber = "Not Available",
                BilledToAddress = "801 ABHISHREE AVENUE OPP. HANUMAN TEMPLE NEHRUNAGAR",
                BilledToCityId = 29,
                BilledToStateId = 1,
                BilledToCountryId = 1,
                BilledToPincode = "380015",
                BilledToGstNumber = "Not Available",
                ShippedToAddress = "801 ABHISHREE AVENUE OPP. HANUMAN TEMPLE NEHRUNAGAR",
                ShippedToCityId = 29,
                ShippedToStateId = 1,
                ShippedToCountryId = 1,
                CustomerIndustryId = 227,
                ShippedToPincode = "380015",
                ShippedToGstNumber = "Not Available",
                IsMsme = true,
                MsmeRegistrationNumber = "Not Available",
                IsContractCustomer = true,
                EffectiveFrom = DateTime.Parse("2023-04-06 15:32:00"),
                EffectiveTo = null,
                IsActive = true,
                IsDeleted = null,
                IsVerified = true,
                CreatedBy = 10,
                CreatedOn = DateTime.Parse("2023-04-06 15:32:00"),
                ModifiedBy = null,
                ModifiedOn = null,
                DeletedBy = null,
                DeletedOn = null
            },
            new CustomerInfo
            {
                Id = 2,
                CustomerId = 2,
                Name = "EDELWEISS RETAIL FINANCE LTD.",
                NameOnPrint = "EDELWEISS RETAIL FINANCE LTD.",
                CustomerGroupId = null,
                TenantOfficeId = 1,
                PrimaryContactName = "MR. KRISHNA MOHAN",
                PrimaryContactEmail = "bismi.sabu@accelits.com",
                PrimaryContactPhone = "40094400",
                PanNumber = "Not Available",
                TinNumber = "Not Available",
                TanNumber = "Not Available",
                CinNumber = "Not Available",
                BilledToAddress = "KOHINOOR CITY, TOWER -3, 3RD FLOOR KIROL ROAD, OFF LBS ROAD, KURLA (WEST), MUMBAI",
                BilledToCityId = 7,
                BilledToStateId = 3,
                BilledToCountryId = 1,
                BilledToPincode = "400070",
                BilledToGstNumber = "Not Available",
                ShippedToAddress = "KOHINOOR CITY, TOWER -3, 3RD FLOOR KIROL ROAD, OFF LBS ROAD, KURLA (WEST), MUMBAI",
                ShippedToCityId = 7,
                ShippedToStateId =3,
                ShippedToCountryId = 1,
                CustomerIndustryId = 226,
                ShippedToPincode = "400070",
                ShippedToGstNumber = "Not Available",
                IsMsme = true,
                MsmeRegistrationNumber = "Not Available",
                IsContractCustomer = true,
                EffectiveFrom = DateTime.Parse("2023-04-06 15:32:00"),
                EffectiveTo = null,
                IsActive = true,
                IsDeleted = null,
                IsVerified = true,
                CreatedBy = 10,
                CreatedOn = DateTime.Parse("2023-04-06 15:32:00"),
                ModifiedBy = null,
                ModifiedOn = null,
                DeletedBy = null,
                DeletedOn = null
            },
            new CustomerInfo
            {
                Id = 3,
                CustomerId = 3,
                Name = "GOKUL AGRI INTERNATIONAL LTD.",
                NameOnPrint = "GOKUL AGRI INTERNATIONAL LTD.",
                CustomerGroupId = null,
                TenantOfficeId = 1,
                PrimaryContactName = "Mr. Rakesh Solanki",
                PrimaryContactEmail = "aravind.balan@accelits.com",
                PrimaryContactPhone = "4009440012",
                PanNumber = "Not Available",
                TinNumber = "Not Available",
                TanNumber = "Not Available",
                CinNumber = "Not Available",
                BilledToAddress = "43, SHREEMALI SOCIETY, OPP SHIKHAR BUILDING NAVRANGPURA",
                BilledToCityId = 29,
                BilledToStateId = 1,
                BilledToCountryId = 1,
                BilledToPincode = "380009",
                BilledToGstNumber = "Not Available",
                ShippedToAddress = "43, SHREEMALI SOCIETY, OPP SHIKHAR BUILDING NAVRANGPURA",
                ShippedToCityId = 29,
                ShippedToStateId = 1,
                ShippedToCountryId = 1,
                CustomerIndustryId = 226,
                ShippedToPincode = "380009",
                ShippedToGstNumber = "Not Available",
                IsMsme = true,
                MsmeRegistrationNumber = "Not Available",
                IsContractCustomer = true,
                EffectiveFrom = DateTime.Parse("2023-04-06 15:32:00"),
                EffectiveTo = null,
                IsActive = true,
                IsDeleted = null,
                IsVerified = true,
                CreatedBy = 10,
                CreatedOn = DateTime.Parse("2023-04-06 15:32:00"),
                ModifiedBy = null,
                ModifiedOn = null,
                DeletedBy = null,
                DeletedOn = null
            },
            new CustomerInfo
            {
                Id = 4,
                CustomerId = 4,
                Name = "UNION BANK OF INDIA REGIONAL OFFICE",
                NameOnPrint = "UNION BANK OF INDIA REGIONAL OFFICE ",
                CustomerGroupId = null,
                TenantOfficeId = 16,
                PrimaryContactName = "Mr. Anil R",
                PrimaryContactEmail = "basith.aa@accelits.com",
                PrimaryContactPhone = "9012874521",
                PanNumber = "Not Available",
                TinNumber = "Not Available",
                TanNumber = "Not Available",
                CinNumber = "Not Available",
                BilledToAddress = "UNION BANK OF INDIA REGIONAL OFFICE",
                BilledToCityId = 13,
                BilledToStateId = 2,
                BilledToCountryId = 1,
                BilledToPincode = "363520",
                BilledToGstNumber = "Not Available",
                ShippedToAddress = "UNION BANK OF INDIA REGIONAL OFFICE",
                ShippedToCityId = 13,
                ShippedToStateId = 2,
                ShippedToCountryId = 1,
                ShippedToPincode = "363520",
                CustomerIndustryId = 226,
                ShippedToGstNumber = "Not Available",
                IsMsme = true,
                MsmeRegistrationNumber = "Not Available",
                IsContractCustomer = true,
                EffectiveFrom = DateTime.Parse("2023-04-06 15:32:00"),
                EffectiveTo = null,
                IsActive = true,
                IsDeleted = null,
                IsVerified = true,
                CreatedBy = 10,
                CreatedOn = DateTime.Parse("2023-04-06 15:32:00"),
                ModifiedBy = null,
                ModifiedOn = null,
                DeletedBy = null,
                DeletedOn = null
            },
            new CustomerInfo
            {
                Id = 5,
                CustomerId = 5,
                Name = "INOX WIND INFRASTRUCTURE SERVICES LTD",
                NameOnPrint = "INOX WIND INFRASTRUCTURE SERVICES LTD",
                CustomerGroupId = null,
                TenantOfficeId = 1,
                PrimaryContactName = "MR VIKRAM BISHT",
                PrimaryContactEmail = "sreerag.hareendran@accelits.com",
                PrimaryContactPhone = "1206149713",
                PanNumber = "Not Available",
                TinNumber = "Not Available",
                TanNumber = "Not Available",
                CinNumber = "Not Available",
                BilledToAddress = "SURVEY NO 71 PART 1 AND 72 PART1, VILLAGE-DEVPURA CHOTTILA DISTRICT,SURENDRA NAGAR",
                BilledToCityId = 29,
                BilledToStateId = 1,
                BilledToCountryId = 1,
                BilledToPincode = "363520",
                BilledToGstNumber = "Not Available",
                ShippedToAddress = "SURVEY NO 71 PART 1 AND 72 PART1, VILLAGE-DEVPURA CHOTTILA DISTRICT,SURENDRA NAGAR",
                ShippedToCityId = 29,
                ShippedToStateId = 1,
                ShippedToCountryId = 1,
                CustomerIndustryId = 226,
                ShippedToPincode = "363520",
                ShippedToGstNumber = "Not Available",
                IsMsme = true,
                MsmeRegistrationNumber = "Not Available",
                IsContractCustomer = true,
                EffectiveFrom = DateTime.Parse("2023-04-06 15:32:00"),
                EffectiveTo = null,
                IsActive = true,
                IsDeleted = null,
                IsVerified = true,
                CreatedBy = 10,
                CreatedOn = DateTime.Parse("2023-04-06 15:32:00"),
                ModifiedBy = null,
                ModifiedOn = null,
                DeletedBy = null,
                DeletedOn = null
            },
            new CustomerInfo
            {
                Id = 6,
                CustomerId = 6,
                Name = "ACCENTURE SERVICES PVT LTD",
                NameOnPrint = "ACCENTURE SERVICES PVT LTD",
                CustomerGroupId = null,
                TenantOfficeId = 1,
                PrimaryContactName = "ACCENTURE",
                PrimaryContactEmail = "shagina.k@accelits.com",
                PrimaryContactPhone = "2204186025",
                PanNumber = "Not Available",
                TinNumber = "Not Available",
                TanNumber = "Not Available",
                CinNumber = "Not Available",
                BilledToAddress = "1ST FLR, TOWER B, BLDG NO 8, D 1ST FLR, TOWER B, BLDG NO 8, D  07122002",
                BilledToCityId = 7,
                BilledToStateId = 3,
                BilledToCountryId = 1,
                BilledToPincode = "363520",
                BilledToGstNumber = "Not Available",
                ShippedToAddress = "1ST FLR, TOWER B, BLDG NO 8, D 1ST FLR, TOWER B, BLDG NO 8, D  07122002",
                ShippedToCityId = 7,
                ShippedToStateId = 3,
                ShippedToCountryId = 1,
                CustomerIndustryId = 226,
                ShippedToPincode = "363520",
                ShippedToGstNumber = "Not Available",
                IsMsme = true,
                MsmeRegistrationNumber = "Not Available",
                IsContractCustomer = true,
                EffectiveFrom = DateTime.Parse("2023-04-06 15:32:00"),
                EffectiveTo = null,
                IsActive = true,
                IsDeleted = null,
                IsVerified = true,
                CreatedBy = 10,
                CreatedOn = DateTime.Parse("2023-04-06 15:32:00"),
                ModifiedBy = null,
                ModifiedOn = null,
                DeletedBy = null,
                DeletedOn = null
            }
            };
        }
    };
}