CREATE OR ALTER PROCEDURE [dbo].[vendor_update]
	@Id INT,
	@TenantOfficeId INT,
	@IsMsme BIT,
	@IsActive BIT,
	@Name VARCHAR(64),
	@Address VARCHAR(128),
	@CityId INT,
	@VendorId INT,
	@StateId INT,
	@CountryId INT,
	@Pincode VARCHAR(6),
	@ContactName VARCHAR(32),
	@Email VARCHAR(64),
	@ContactNumberOneCountryCode VARCHAR(8),
	@ContactNumberOne VARCHAR(16),
	@ContactNumberTwoCountryCode VARCHAR(8),
	@ContactNumberTwo VARCHAR(16),
	@CreditPeriodInDays INT,
	@GstNumber VARCHAR(16),
	@GstVendorTypeId INT,
	@ArnNumber VARCHAR(16),
	@EsiNumber VARCHAR(17),
	@PanNumber VARCHAR(10),
	@PanTypeId INT,
	@VendorTypeId INT,
	@TanNumber VARCHAR(10),
	@CinNumber VARCHAR(21),
	@MsmeRegistrationNumber VARCHAR(16)=NULL,
	@MsmeCommencementDate DATE=NULL,
	@MsmeExpiryDate DATE=NULL,
	@UpdatedBy INT
AS
BEGIN
SET NOCOUNT ON;
SET XACT_ABORT ON;  
BEGIN TRANSACTION
	INSERT INTO VendorInfo
		(VendorId,
		TenantOfficeId,
		[Name],
		[Address],	
		CityId,
		StateId,
		CountryId,
		Pincode,
		ContactName,
		Email,
		ContactNumberOneCountryCode,
		ContactNumberOne,
		ContactNumberTwoCountryCode,
		ContactNumberTwo,
		CreditPeriodInDays,
		GstNumber,
		GstVendorTypeId,
		ArnNumber,
		EsiNumber,
		PanNumber,
		PanTypeId,
		VendorTypeId,
		TanNumber,
		CinNumber,
		IsMsme,
		IsActive,
		MsmeRegistrationNumber,
		MsmeCommencementDate,
		MsmeExpiryDate,
		EffectiveFrom,
		CreatedBy,
		CreatedOn)
		VALUES
		(@VendorId,
		@TenantOfficeId,
		@Name,
		@Address,	
		@CityId,
		@StateId,
		@CountryId,
		@Pincode,
		@ContactName,
		@Email,
		@ContactNumberOneCountryCode,
		@ContactNumberOne,
		@ContactNumberTwoCountryCode,
		@ContactNumberTwo,
		@CreditPeriodInDays,
		@GstNumber,
		@GstVendorTypeId,
		@ArnNumber,
		@EsiNumber,
		@PanNumber,
		@PanTypeId,
		@VendorTypeId,
		@TanNumber,
		@CinNumber,
		@IsMsme,
		@IsActive,
		@MsmeRegistrationNumber,
		@MsmeCommencementDate,
		@MsmeExpiryDate,
		GETUTCDATE(),
		@UpdatedBy,
		GETUTCDATE())

		UPDATE 
			VendorInfo
		SET 
			IsActive = 0,
			EffectiveTo = GETUTCDATE(),
			UpdatedBy = @UpdatedBy,
			UpdatedOn = GETUTCDATE()
		WHERE 
			Id = @Id
COMMIT TRANSACTION;
END