
using database.Models;

namespace database.Seeder.Staging
{
    public class AssetProductCategorySeeder
    {
        public IEnumerable<AssetProductCategory> GetData()
        {
            return new List<AssetProductCategory>
            {
            new AssetProductCategory { Id=1, Code="R001", CategoryName="AIO Desktop", PartProductCategoryId=1,GeneralNotCovered="",SoftwareNotCovered="",HardwareNotCovered="", CreatedBy=10, CreatedOn=DateTime.Parse("2024-04-16 10:10:10") },
            new AssetProductCategory { Id=2, Code="R002", CategoryName="Barcode Printer", PartProductCategoryId=7, GeneralNotCovered="Outer Cover, Physical damage, Burnt , Plastic Parts,Consumables",SoftwareNotCovered="Drivers(Media /License has to be provided by customer)",HardwareNotCovered="Print head", CreatedBy=10, CreatedOn=DateTime.Parse("2024-04-16 10:10:10") },
            new AssetProductCategory { Id=3, Code="R003", CategoryName="Barcode Scanner", PartProductCategoryId=9,GeneralNotCovered="Outer cover, Physical damage, Burnt part, Cables",SoftwareNotCovered="Drivers(Media /License has to be provided by customer)",HardwareNotCovered="",  CreatedBy=10, CreatedOn=DateTime.Parse("2024-04-16 10:10:10") },
            new AssetProductCategory { Id=4, Code="R004", CategoryName="Desktop", PartProductCategoryId=2,GeneralNotCovered="Outer Cover, Physical damage, Burnt , Plastic Parts, Datas and Data Backup, Any external devices /Add ons",SoftwareNotCovered="O/s & Drivers , Firmware, Patches (Media /License has to be provided by customer)",HardwareNotCovered="CRT  / TFT panel",  CreatedBy=10, CreatedOn=DateTime.Parse("2024-04-16 10:10:10") },
            new AssetProductCategory { Id=5, Code="R005", CategoryName="Dot Matrix Printer", PartProductCategoryId=7, GeneralNotCovered="Outer Cover, Physical damage, Burnt , Plastic Parts , Raibbon Cartridge,Consumables",SoftwareNotCovered="Drivers(Media /License has to be provided by customer)",HardwareNotCovered="Print head", CreatedBy=10, CreatedOn=DateTime.Parse("2024-04-16 10:10:10") },
            new AssetProductCategory { Id=6, Code="R006", CategoryName="Firewall", PartProductCategoryId=4,GeneralNotCovered="Outer Cover, Physical damage, Burnt , Plastic Parts",SoftwareNotCovered=" Firmware, Patches (Media /License has to be provided by customer)",HardwareNotCovered="",  CreatedBy=10, CreatedOn=DateTime.Parse("2024-04-16 10:10:10") },
            new AssetProductCategory { Id=7, Code="R007", CategoryName="Hub", PartProductCategoryId=4,GeneralNotCovered="Outer Cover, Physical damage, Burnt , Plastic Parts",SoftwareNotCovered=" Firmware, Patches (Media /License has to be provided by customer)",HardwareNotCovered="",  CreatedBy=10, CreatedOn=DateTime.Parse("2024-04-16 10:10:10") },
            new AssetProductCategory { Id=8, Code="R008", CategoryName="Inkjet Printer", PartProductCategoryId=7, GeneralNotCovered="Outer Cover, Physical damage, Burnt , Plastic Parts , Ink Cartridge, Consumables",SoftwareNotCovered="Drivers(Media /License has to be provided by customer)",HardwareNotCovered="Print Head", CreatedBy=10, CreatedOn=DateTime.Parse("2024-04-16 10:10:10") },
            new AssetProductCategory { Id=9, Code="R009", CategoryName="Laptop", PartProductCategoryId=3, GeneralNotCovered="Outer Cover, Burnt , Plastic Parts, Datas and Data Backup, Any external devices /Add onsv",SoftwareNotCovered="O/s & Drivers , Firmware, Patches (Media /License has to be provided by customer)",HardwareNotCovered="LCD panel , Battery , Hinges", CreatedBy=10, CreatedOn=DateTime.Parse("2024-04-16 10:10:10") },
            new AssetProductCategory { Id=10, Code="R010", CategoryName="Laser Printer", PartProductCategoryId=7,GeneralNotCovered="Outer Cover, Physical damage, Burnt , Plastic Parts , Tonar Cartridge, consumables",SoftwareNotCovered="Drivers(Media /License has to be provided by customer)",HardwareNotCovered="Maintenance kit",  CreatedBy=10, CreatedOn=DateTime.Parse("2024-04-16 10:10:10") },
            new AssetProductCategory { Id=11, Code="R011", CategoryName="Line Printer", PartProductCategoryId=7,GeneralNotCovered="Outer Cover, Physical damage, Burnt , Plastic Parts , Raibbon Cartridge, Consumables",SoftwareNotCovered="Drivers(Media /License has to be provided by customer)",HardwareNotCovered="Fret /Shuttle Assy/Print Head",  CreatedBy=10, CreatedOn=DateTime.Parse("2024-04-16 10:10:10") },
            new AssetProductCategory { Id=12, Code="R012", CategoryName="Misc", PartProductCategoryId=5, GeneralNotCovered="Outer Cover, Physical damage, Burnt , Plastic Parts",SoftwareNotCovered=" Firmware, Patches (Media /License has to be provided by customer)",HardwareNotCovered="", CreatedBy=10, CreatedOn=DateTime.Parse("2024-04-16 10:10:10") },
            new AssetProductCategory { Id=13, Code="R013", CategoryName="Modem", PartProductCategoryId=4,GeneralNotCovered="Outer Cover, Physical damage, Burnt , Plastic Parts",SoftwareNotCovered=" Firmware, Patches (Media /License has to be provided by customer)",HardwareNotCovered="",  CreatedBy=10, CreatedOn=DateTime.Parse("2024-04-16 10:10:10") },
            new AssetProductCategory { Id=14, Code="R014", CategoryName="Monitor", PartProductCategoryId=2, GeneralNotCovered="Outer Cover, Physical damage, Burnt , Plastic Parts , Mura",SoftwareNotCovered="",HardwareNotCovered="CRT picture tube / TFT panel", CreatedBy=10, CreatedOn=DateTime.Parse("2024-04-16 10:10:10") },
            new AssetProductCategory { Id=15, Code="R015", CategoryName="NW Misc", PartProductCategoryId=4,GeneralNotCovered="Outer Cover, Physical damage, Burnt , Plastic Parts",SoftwareNotCovered=" Firmware, Patches (Media /License has to be provided by customer)",HardwareNotCovered="",  CreatedBy=10, CreatedOn=DateTime.Parse("2024-04-16 10:10:10") },
            new AssetProductCategory { Id=16, Code="R016", CategoryName="Others", PartProductCategoryId=5, GeneralNotCovered="Outer Cover, Physical damage, Burnt part,Consumables",SoftwareNotCovered="",HardwareNotCovered="", CreatedBy=10, CreatedOn=DateTime.Parse("2024-04-16 10:10:10") },
            new AssetProductCategory { Id=17, Code="R017", CategoryName="Pagewide", PartProductCategoryId=7, GeneralNotCovered="",SoftwareNotCovered="",HardwareNotCovered="", CreatedBy=10, CreatedOn=DateTime.Parse("2024-04-16 10:10:10") },
            new AssetProductCategory { Id=18, Code="R018", CategoryName="Passbook Printer", PartProductCategoryId=7,GeneralNotCovered="Outer Cover, Physical damage, Burnt , Plastic Parts,Consumables",SoftwareNotCovered="Drivers(Media /License has to be provided by customer)",HardwareNotCovered="Print head",  CreatedBy=10, CreatedOn=DateTime.Parse("2024-04-16 10:10:10") },
            new AssetProductCategory { Id=19, Code="R019", CategoryName="Plotter", PartProductCategoryId=6, GeneralNotCovered="Outer Cover, Physical damage, Burnt part, Consumables, Cartridges",SoftwareNotCovered="Drivers , Firmware, Patches (Media /License has to be provided by customer)",HardwareNotCovered="Print Head", CreatedBy=10, CreatedOn=DateTime.Parse("2024-04-16 10:10:10") },
            new AssetProductCategory { Id=20, Code="R020", CategoryName="POS", PartProductCategoryId=2, GeneralNotCovered="Outer Cover, Physical damage, Burnt , Plastic Parts, Datas and Data Backup, Any external devices /Add ons",SoftwareNotCovered="O/s & Drivers , Firmware, Patches (Media /License has to be provided by customer)",HardwareNotCovered="CRT  / TFT panel", CreatedBy=10, CreatedOn=DateTime.Parse("2024-04-16 10:10:10") },
            new AssetProductCategory { Id=21, Code="R021", CategoryName="POS Printer", PartProductCategoryId=7,GeneralNotCovered="Outer Cover, Physical damage, Burnt , Plastic Parts,Consumables",SoftwareNotCovered="Drivers(Media /License has to be provided by customer)",HardwareNotCovered="Print head",  CreatedBy=10, CreatedOn=DateTime.Parse("2024-04-16 10:10:10") },
            new AssetProductCategory { Id=22, Code="R022", CategoryName="Projector", PartProductCategoryId=8, GeneralNotCovered="",SoftwareNotCovered="",HardwareNotCovered="", CreatedBy=10, CreatedOn=DateTime.Parse("2024-04-16 10:10:10") },
            new AssetProductCategory { Id=23, Code="R023", CategoryName="Router", PartProductCategoryId=4, GeneralNotCovered="Outer Cover, Physical damage, Burnt , Plastic Parts",SoftwareNotCovered=" Firmware, Patches (Media /License has to be provided by customer)",HardwareNotCovered="", CreatedBy=10, CreatedOn=DateTime.Parse("2024-04-16 10:10:10") },
            new AssetProductCategory { Id=24, Code="R024", CategoryName="Scanner", PartProductCategoryId=9, GeneralNotCovered="Outer cover, Physical damage, Burnt part",SoftwareNotCovered="Drivers(Media /License has to be provided by customer)",HardwareNotCovered="Maintenance kit", CreatedBy=10, CreatedOn=DateTime.Parse("2024-04-16 10:10:10") },
            new AssetProductCategory { Id=25, Code="R025", CategoryName="Server", PartProductCategoryId=10,GeneralNotCovered="Outer Cover, Physical damage, Burnt , Plastic Parts, Datas and Data Backup, Any external devices /Add ons",SoftwareNotCovered="O/s & Drivers , Firmware, Patches (Media /License has to be provided by customer)",HardwareNotCovered="Raid card battery",  CreatedBy=10, CreatedOn=DateTime.Parse("2024-04-16 10:10:10") },
            new AssetProductCategory { Id=26, Code="R026", CategoryName="Storage", PartProductCategoryId=11,GeneralNotCovered="Outer Cover, Physical damage, Burnt , Plastic Parts, Datas and Data Backup,Media, Any external devices /Add ons",SoftwareNotCovered="O/s & Drivers , Firmware, Patches (Media /License has to be provided by customer)",HardwareNotCovered="Cache battery",  CreatedBy=10, CreatedOn=DateTime.Parse("2024-04-16 10:10:10") },
            new AssetProductCategory { Id=27, Code="R027", CategoryName="Switch", PartProductCategoryId=4,GeneralNotCovered="Outer Cover, Physical damage, Burnt , Plastic Parts",SoftwareNotCovered=" Firmware, Patches (Media /License has to be provided by customer)",HardwareNotCovered="",  CreatedBy=10, CreatedOn=DateTime.Parse("2024-04-16 10:10:10") },
            new AssetProductCategory { Id=28, Code="R028", CategoryName="Thin Client", PartProductCategoryId=2, GeneralNotCovered="Outer Cover, Physical damage, Burnt , Plastic Parts, Datas and Data Backup, Any external devices /Add ons",SoftwareNotCovered="O/s & Drivers , Firmware, Patches (Media /License has to be provided by customer)",HardwareNotCovered="CRT  / TFT panel", CreatedBy=10, CreatedOn=DateTime.Parse("2024-04-16 10:10:10") },
            new AssetProductCategory { Id=29, Code="R029", CategoryName="UPS", PartProductCategoryId=12, GeneralNotCovered="Outer Cover, Physical damage, Burnt part,Consumables",SoftwareNotCovered="",HardwareNotCovered="Battery", CreatedBy=10, CreatedOn=DateTime.Parse("2024-04-16 10:10:10") },
            new AssetProductCategory { Id=30, Code="R030", CategoryName="Workstation", PartProductCategoryId=13,GeneralNotCovered="Outer Cover, Physical damage, Burnt , Plastic Parts, Datas and Data Backup, Any external devices /Add ons",SoftwareNotCovered="O/s & Drivers , Firmware, Patches (Media /License has to be provided by customer)",HardwareNotCovered="CRT  / TFT panel",  CreatedBy=10, CreatedOn=DateTime.Parse("2024-04-16 10:10:10") },            };
        }
    }
}