namespace BeSureApi.Authorization.BusinessFunctionCode
{
    public class ContractBusinessFunctionCode
    {
        public const string CONTRACT_CREATE = "CONTRACT_CREATE";
        public const string CONTRACT_VIEW = "CONTRACT_VIEW";
        public const string CONTRACT_REVIEW = "CONTRACT_REVIEW";
        public const string CONTRACT_ASSET = "CONTRACT_ASSET";
        public const string CONTRACT_CUSTOMER_SITE_CREATE = "CONTRACT_CUSTOMER_SITE_CREATE";
        public const string CONTRACT_ACCOUNTS = "CONTRACT_ACCOUNTS";
        public const string CONTRACT_BANK_GUARANTEE_EDIT = "CONTRACT_BANK_GUARANTEE_EDIT";
        public const string CONTRACT_BANK_GUARANTEE_CREATE = "CONTRACT_BANK_GUARANTEE_CREATE";
        public const string CONTRACT_BANK_GUARANTEE_LIST = "CONTRACT_BANK_GUARANTEE_LIST";
        public const string CONTRACT_RENEW = "CONTRACT_RENEW";
        public const string REVENUERECOGNITION_LIST = "REVENUERECOGNITION_LIST";
        public const string CONTRACT_DASHBOARD_BOOKINGDETAIL_VIEW = "CONTRACT_DASHBOARD_BOOKINGDETAIL_VIEW";
        public const string CONTRACT_DASHBOARD_INVOICECOLLECTION_MADE_VIEW = "CONTRACT_DASHBOARD_INVOICECOLLECTION_MADE_VIEW";
        public const string CONTRACT_DASHBOARD_INVOICECOLLECTION_PENDING_VIEW = "CONTRACT_DASHBOARD_INVOICECOLLECTION_PENDING_VIEW";
        public const string CONTRACT_DASHBOARD_INVOICES_RAISED_VIEW = "CONTRACT_DASHBOARD_INVOICES_RAISED_VIEW";
        public const string CONTRACT_DASHBOARD_INVOICECOLLECTION_OUTSTANDING_VIEW = "CONTRACT_DASHBOARD_INVOICECOLLECTION_OUTSTANDING_VIEW";
        public const string CONTRACT_DASHBOARD_REVENUERECOGNITION_VIEW = "CONTRACT_DASHBOARD_REVENUERECOGNITION_VIEW";
    }
}
